id = "github-dark-dimmed"
name = "GitHub Dark Dimmed"
version = "0.1.1"
schema_version = 1
authors = ["nian1 <nian1.wiki@gmail.com>"]
description = "GitHub Dark Dimmed theme for Zed"
repository = "https://github.com/syxc/github-dark-dimmed-zed"
